# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
test:
  adapter: mysql2
  encoding: utf8
  database: railsapp_test
  username: root
  password: 10faba96
  pool: 5
  host: 10.200.3.71
  port: 3306

development:
  adapter: mysql2
  encoding: utf8
  database: railsapp_development
  username: root
  password: 10faba96
  pool: 5
  host: 10.200.3.71
  port: 3306

production:
  adapter: mysql
  encoding: utf8
  database: railsapp_production
  username: root
  password: 10faba96
  host: 10.200.3.71
  port: 3306
